theme: jekyll-theme-cayman
title: Udacity Google India Scholarship program
description: List of projects created as part of Udacity Android Basics course
plugins:
  - jemoji
github:
  is_project_page: true
